#!/usr/bin/env bash


if [ "${whoami}" == "root" ]; then
	echo "This script must be run by non-root users only."
	exit 1
fi

if [ -z $1 ]; then
	echo "Need version as first argument."
	exit 1
fi

OLD="valet-php@$(php -v | sed -n 's/PHP\ \(.*\)/\1/p' | head -c 3)"
NEW="valet-php@${1}"

function activate_old()
{
	echo "Activating ${OLD}.."
	brew link $OLD
	sudo brew services restart $OLD
}
function deactivate_old()
{
	echo "Deactivating ${OLD}.."
	brew unlink $OLD
	sudo brew services stop $OLD
}
function activate_new()
{
	echo "Activating ${NEW}.."
	brew link $NEW
	sudo brew services restart $NEW
}
function deactivate_new()
{
	echo "Deactivating ${NEW}.."
	brew unlink $NEW
	sudo brew services stop $NEW
}


if [ $(brew info $OLD | grep -c "Not installed") -eq 1 ]; then
	echo "${OLD} is not installed, only going to activate ${NEW}."
	activate_new
else 
	if [ $(brew info $NEW | grep -c "Not installed") -eq 1 ]; then
		echo "${NEW} not found locally, building from source.."
		brew install --build-from-source $NEW
		if [ $? -gt 0 ]; then
			activate_old
			exit 2
		fi
	fi
	deactivate_old && activate_new
fi

exit $?


echo "Enabling ${NEW}.."
brew link $NEW
sudo brew services restart $NEW
